---
- name: Prepare ArchLinux Distributions
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: ensure Python and Grep are installed
      ansible.builtin.raw: pacman -Sy --noconfirm python grep

- name: Prepare Debian Distributions
  hosts: debian
  gather_facts: false
  tasks:
    - name: update package cache
      ansible.builtin.raw: apt-get update
    - name: ensure Python is installed
      ansible.builtin.raw: apt-get install -y python3

- name: Prepare RedHat Distributions
  hosts: redhat
  gather_facts: false
  tasks:
    - name: ensure Python is installed
      ansible.builtin.raw: yum install -y python36
