---
- name: Prepare ArchLinux Distributions
  hosts: archlinux
  gather_facts: false
  tasks:
    - name: Ensure Python and Grep are installed
      raw: pacman -Sy --noconfirm python grep

- name: Prepare Debian Distributions
  hosts: debian
  gather_facts: false
  tasks:
    - name: Update package cache
      raw: apt-get update
    - name: Ensure Python is installed
      raw: apt-get install -y python3

- name: Prepare RedHat Distributions
  hosts: redhat
  gather_facts: false
  tasks:
    - name: Ensure Python is installed
      raw: yum install -y python36
